name: '[Support] Synchronize team members in the .env file'
on:
  schedule:
    # Daily
    - cron: '0 5 * * *'
# Remove all permissions by default. Write actions are done by Symas Bot
permissions: {}
jobs:
  sync-support-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SYMAS_BOT_TOKEN }}
          fetch-depth: 1
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: .github/workflows/
      - name: Updating members of the Symas team
        run: |
          TEAM_MEMBERS=$(curl --request GET \
          --url https://api.github.com/orgs/symas/teams/developers/members?per_page=100 \
          --header 'authorization: Bearer ${{ secrets.SYMAS_BOT_TOKEN }}' \
          --header 'content-type: application/json' \
          | jq 'sort_by(.login)|map(.login)|join(",")')
          TEAM_MEMBERS='['${TEAM_MEMBERS//','/'","'}']'
          if [ $TEAM_MEMBERS != $SYMAS_TEAM ]; then
            echo "Replacing $SYMAS_TEAM for $TEAM_MEMBERS"
            sed -i "s|SYMAS_TEAM=.*$|SYMAS_TEAM='${TEAM_MEMBERS}'|g" .github/workflows/.env
            git config user.name "symas-bot"
            git config user.email "symas-bot@symas.com"
            git commit -s -m"[symas-bot] Updating Symas team members" .github/workflows/.env
            git push
          else
            echo "SYMAS_TEAM is updated and nothing should be done"
          fi
